### PR TITLE
Clicking on "view" now works.

### PR DESCRIPTION
**Pull request by xuericlin**
Now clicking view comments should send you directly to the comments!

Emoji problem can be resolved here:
'\xF0\x9F\x98\x83\xF0\x9F...' for column 'comment' at row 1
- need to change database
https://stackoverflow.com/questions/39463134/how-to-store-emoji-character-in-mysql-database

Original issue was in how we parse .json file links -> mapping url to url.json files.

### CODE REVIEW

**Comment by amyxzhang** [comment]
Hi! can you get rid of the print statements in the pull request? @xuericlin

**Comment by xuericlin** [comment]
Yup, I also made some edge case edits on the code and cleaned up the code a
bit. Left some comments in the code case but will remove later when I
receive an ok.

**Comment by amyxzhang** [comment]
@xuericlin do you see the merge conflict above? Would you able to fix that too? I'm not sure how to resolve it.

**Comment by xuericlin** [comment]
Just resolved the merge conflict. I commented out the code that I don't believe was in my code originally. I don't think it seemed to be doing anything though. Could you check now?

**Comment by xuericlin** [comment]
Hi Amy,

I just merged and resolved the pull request. I left a comment on the pull
request about what I did as well. We should also note to resolve the emoji
issue, and I can take a look into that on the side.

Does the current wikum.org not have the summarize + highlight as an option
anymore? The UI is different from what is on localhost. And could we catch
up later today on this topic since I want to do user testing on this. Not
sure how long the paperwork would take so I would like to start on those
early.

- Eric

**Comment by xuericlin** [comment]
I also remember that the "highlight sentences" would work before, but I
don't think it highlights anymore? It might just be the samples I'm testing
but none of them are highlighting. Do you know if a recent change has
caused it or am I missing something?

**Comment by xuericlin** [comment]
Ah, could this be the issue?
[image: Screen Shot 2020-03-03 at 1.42.55 PM.png]

**Comment by amyxzhang** [comment]
Hi @xuericlin let's keep comments in this pull request focused on the pull request itself.

**Comment by amyxzhang** [comment]
Also in the future, please let me be the one to merge pull requests.

**Pull request merged**
